language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - Gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-6.0.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails-master.gemfile
      rvm: 2.4.9
    - gemfile: gemfiles/rails-6.0.gemfile
      rvm: 2.4.9
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
